# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-30 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=30)),
                ('health', models.IntegerField()),
                ('armour', models.IntegerField()),
                ('shield', models.IntegerField()),
                ('real_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('affiliation', models.CharField(max_length=50)),
                ('base_of_operation', models.CharField(max_length=50)),
                ('avatar', models.URLField()),
                ('bio', models.CharField(max_length=200)),
            ],
        ),
    ]
