# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-22 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
